# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_posts_from_fixture(apps, schema_editor):
    call_command("loaddata", "post")

def delete_posts(apps, schema_editor):
    post = apps.get_model('post', 'Post')
    post.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_posts_from_fixture, delete_posts),
    ]
