# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_teams_from_fixture(apps, schema_editor):
    call_command("loaddata", "team")


def delete_teams(apps, schema_editor):
    team = apps.get_model('team', 'Team')
    team.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
        ('team', '0002_team_name_unique')
    ]

    operations = [
        migrations.RunPython(load_teams_from_fixture, delete_teams),
    ]
