# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_messages_from_fixture(apps, schema_editor):
    call_command("loaddata", "messages")


def delete_messages(apps, schema_editor):
    messages = apps.get_model('team', 'RequestUserTeam')
    messages.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('team', '0001_initial'),
        ('team', '0002_team_name_unique'),
        ('team', '0003_seeds')
    ]

    operations = [
        migrations.RunPython(load_messages_from_fixture, delete_messages),
    ]
