# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.directory_path),
        ),
    ]
