# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 20:12
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.directory_path),
        ),
    ]
