# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from datetime import date, datetime

from django.db import migrations
from django.contrib.auth.models import User
from django.core.management import call_command

from account.models import Profile
from team.models import Team


def load_accounts_from_fixture(apps, schema_editor):
    call_command("loaddata", "account")

    users = User.objects.all()

    for user in users:
        Profile.objects.get_or_create(user=user)
        user.set_password(user.password)
        user.save()

    first_team_users = User.objects.all()[1:5]
    for user in first_team_users:
        user.profile.team = Team.objects.get(id=0)
        user.profile.save()

    second_team_users = User.objects.all()[5:8]
    for user in second_team_users:
        user.profile.team = Team.objects.get(id=1)
        user.profile.save()

    third_team_users = User.objects.all()[8:10]
    for user in third_team_users:
        user.profile.team = Team.objects.get(id=2)
        user.profile.save()

    fourth_team_user = User.objects.get(id=11)
    fourth_team_user.profile.team = Team.objects.get(id=3)
    fourth_team_user.profile.save()

    fifth_team_user = User.objects.get(id=12)
    fifth_team_user.profile.team = Team.objects.get(id=4)
    fifth_team_user.profile.save()

    sixth_team_user = User.objects.get(id=13)
    sixth_team_user.profile.team = Team.objects.get(id=5)
    sixth_team_user.profile.save()


def delete_accounts(apps, schema_editor):
    account = apps.get_model('auth', 'User')
    account.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
        ('account', '0002_profile_image'),
        ('team', '0001_initial'),
        ('team', '0002_team_name_unique'),
        ('team', '0003_seeds')

    ]

    operations = [
        migrations.RunPython(load_accounts_from_fixture, delete_accounts),
    ]
