# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_vips_from_fixture(apps, schema_editor):
    call_command("loaddata", "vip")
    call_command("loaddata", "lecture")


def delete_vips(apps, schema_editor):
    vip = apps.get_model('vip', 'Vip')
    vip.objects.all().delete()

def delete_lecturers(apps, schema_editor):
    lecture = apps.get_model('vip', 'Lesson')
    lecture.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_vips_from_fixture, delete_vips, delete_lecturers),
    ]
