# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations


def load_awards_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "award")


def delete_awards(apps, schema_editor):
    award = apps.get_model("award", "Award")
    award.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_awards_from_fixture, delete_awards),
    ]
