# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.directory_path),
        ),
    ]
