# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:55
from __future__ import unicode_literals

from django.db import migrations


def load_games_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "game")

def delete_games(apps, schema_editor):
    game = apps.get_model('game', 'Game')
    game.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
        ('game', '0002_add_fields'),
        ('team', '0001_initial'),
        ('team', '0002_team_name_unique'),
        ('team', '0003_seeds')
    ]

    operations = [
        migrations.RunPython(load_games_from_fixture, delete_games),
    ]
