# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
