# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180602_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
