# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('email', models.EmailField(default='a@b.c', max_length=254)),
                ('contest_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
